services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - db_mysql_data:/var/lib/mysql
    networks:
      eclassapi_network:
        aliases:
          - db_eclass_net
  
  app:
    build: ./
    container_name: express_app
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
    networks:
      eclassapi_network:
        aliases:
          - app_eclass_net

volumes:
  db_mysql_data:

networks:
  eclassapi_network:
    name: eclassapi_net
    driver: bridge